//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34014
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KH_Central.OfficeSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KH_Central.OfficeSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap admissions_zoom_64 {
            get {
                object obj = ResourceManager.GetObject("admissions_zoom_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap columchart_zoom_64 {
            get {
                object obj = ResourceManager.GetObject("columchart_zoom_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap companies_save_64 {
            get {
                object obj = ResourceManager.GetObject("companies_save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ftp_site_64 {
            get {
                object obj = ResourceManager.GetObject("ftp_site_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap system_zoom_64 {
            get {
                object obj = ResourceManager.GetObject("system_zoom_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;root&gt;
        ///	&lt;局端檢核 學年度=&quot;99&quot; 學期=&quot;2&quot; 名冊名稱=&quot;99_2_中輟學生名冊&quot; 名冊類別=&quot;中輟學生名冊&quot; 檢核狀態=&quot;完成&quot; 檢核日期=&quot;2013/1/1&quot; 核准文號=&quot;高市教二字第001號&quot;/&gt;
        ///	&lt;局端檢核 學年度=&quot;99&quot; 學期=&quot;2&quot; 名冊名稱=&quot;99_2_休學學生名冊&quot; 名冊類別=&quot;休學學生名冊&quot; 檢核狀態=&quot;完成&quot; 檢核日期=&quot;2013/1/2&quot; 核准文號=&quot;高市教二字第002號&quot;/&gt;
        ///	&lt;局端檢核 學年度=&quot;99&quot; 學期=&quot;2&quot; 名冊名稱=&quot;99_2_復學學生名冊&quot; 名冊類別=&quot;復學學生名冊&quot; 檢核狀態=&quot;完成&quot; 檢核日期=&quot;2013/1/3&quot; 核准文號=&quot;高市教二字第003號&quot;/&gt;
        ///	&lt;局端檢核 學年度=&quot;99&quot; 學期=&quot;2&quot; 名冊名稱=&quot;99_2_新生名冊&quot; 名冊類別=&quot;新生學生名冊&quot; 檢核狀態=&quot;完成&quot; 檢核日期=&quot;2013/1/4&quot; 核准文號=&quot;高市教二字第004號&quot;/&gt;
        ///	&lt;局端檢核 學年度=&quot;99&quot; 學期=&quot;2&quot; 名冊名稱=&quot;99_2_畢業名冊&quot; 名冊類別=&quot;畢業學生名冊&quot; 檢核狀態=&quot;完成&quot; 檢核日期=&quot;2013/1/5&quot; 核准文號=&quot;高市教二字第00 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string temp {
            get {
                return ResourceManager.GetString("temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 高雄市區里測試 {
            get {
                object obj = ResourceManager.GetObject("高雄市區里測試", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
