//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KH_Central.OfficeSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KH_Central.OfficeSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap companies_save_64 {
            get {
                object obj = ResourceManager.GetObject("companies_save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;
        ///	&lt;局端檢核 學年度=&quot;99&quot; 學期=&quot;2&quot; 名冊名稱=&quot;99_2_中輟學生名冊&quot; 名冊類別=&quot;中輟學生名冊&quot; 檢核狀態=&quot;完成&quot; 檢核日期=&quot;2013/1/1&quot; 核准文號=&quot;高市教二字第001號&quot;/&gt;
        ///	&lt;局端檢核 學年度=&quot;99&quot; 學期=&quot;2&quot; 名冊名稱=&quot;99_2_休學學生名冊&quot; 名冊類別=&quot;休學學生名冊&quot; 檢核狀態=&quot;完成&quot; 檢核日期=&quot;2013/1/2&quot; 核准文號=&quot;高市教二字第002號&quot;/&gt;
        ///	&lt;局端檢核 學年度=&quot;99&quot; 學期=&quot;2&quot; 名冊名稱=&quot;99_2_復學學生名冊&quot; 名冊類別=&quot;復學學生名冊&quot; 檢核狀態=&quot;完成&quot; 檢核日期=&quot;2013/1/3&quot; 核准文號=&quot;高市教二字第003號&quot;/&gt;
        ///	&lt;局端檢核 學年度=&quot;99&quot; 學期=&quot;2&quot; 名冊名稱=&quot;99_2_新生名冊&quot; 名冊類別=&quot;新生學生名冊&quot; 檢核狀態=&quot;完成&quot; 檢核日期=&quot;2013/1/4&quot; 核准文號=&quot;高市教二字第004號&quot;/&gt;
        ///	&lt;局端檢核 學年度=&quot;99&quot; 學期=&quot;2&quot; 名冊名稱=&quot;99_2_畢業名冊&quot; 名冊類別=&quot;畢業學生名冊&quot; 檢核狀態=&quot;完成&quot; 檢核日期=&quot;2013/1/5&quot; 核准文號=&quot;高市教二字第00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string temp {
            get {
                return ResourceManager.GetString("temp", resourceCulture);
            }
        }
        
        internal static byte[] 高雄市區里測試 {
            get {
                object obj = ResourceManager.GetObject("高雄市區里測試", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
